import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'rn';

const translations = {
  en: {
    nav_home: 'Home',
    nav_soko: 'Soko',
    nav_sell: 'Sell',
    nav_inbox: 'Inbox',
    nav_profile: 'Profile',
    buy_via_soko: 'Buy via Soko-Live',
    switch_to_seller: 'Switch to Seller',
    escrow_status: 'Funds held in Escrow',
    ad_placeholder: 'Sponsored Ad',
    upload_product: 'Upload Product',
    chat_empty: 'No messages yet',
    role_buyer: 'Role: Buyer',
    role_seller: 'Role: Seller',
    enter_cni: 'Enter CNI (ID) to become a seller',
    submit: 'Submit',
    message_seller_privately: 'Message Seller Privately',
    comments: 'Comments',
    write_comment: 'Write a comment...',
    seller_badge: 'Seller',
    report: 'Report',
    confirm_purchase: 'Confirm Purchase',
    ask_question: 'Ask a question',
    proceed_to_payment: 'Proceed to Payment',
    interested_in: "Hi! I'm interested in your {product} from the feed.",
    search_placeholder: 'Search products...',
    filter: 'Filter',
    condition_new: 'New',
    condition_used: 'Used',
    all: 'All',
    clothes: 'Clothes',
    tech: 'Tech',
    food: 'Food',
    cars: 'Cars',
    sub_categories: 'Sub-categories',
    price_range: 'Price Range',
    clear_all: 'Clear All',
    apply_filters: 'Apply Filters',
    no_results: 'No results found',
    clear_filters_to_see_more: 'Clear filters to see more',
    shoes: 'Shoes',
    phones: 'Phones',
    furniture: 'Furniture',
    search_categories: 'Search categories...',
    more: 'More',
    back_to_top: 'Back to Top',
    electronics: 'Electronics',
    beauty: 'Beauty',
    sports: 'Sports',
    home_garden: 'Home & Garden',
    baby: 'Baby',
    books: 'Books',
    services: 'Services',
    real_estate: 'Real Estate',
    solar_energy: 'Solar Energy',
    agriculture: 'Agriculture',
    hardware: 'Hardware',
    beverages: 'Beverages (Amayoga)',
    industrial_tools: 'Industrial Tools',
    share: 'Share',
    joined: 'Joined',
    view_shop: 'View Shop',
    message_seller: 'Message Seller',
    buy_now: 'BUY NOW',
    verified_soko_point: 'Verified Soko-Point',
    you_might_also_like: 'You might also like',
    read_more: 'Read more',
    read_less: 'Read less',
    more_from_seller: 'More from this Seller',
    share_success: 'Link copied to clipboard!',
  },
  fr: {
    nav_home: 'Accueil',
    nav_soko: 'Soko',
    nav_sell: 'Vendre',
    nav_inbox: 'Boîte',
    nav_profile: 'Profil',
    buy_via_soko: 'Acheter via Soko-Live',
    switch_to_seller: 'Devenir Vendeur',
    escrow_status: 'Fonds bloqués (Escrow)',
    ad_placeholder: 'Annonce Sponsorisée',
    upload_product: 'Ajouter un produit',
    chat_empty: 'Aucun message',
    role_buyer: 'Rôle: Acheteur',
    role_seller: 'Rôle: Vendeur',
    enter_cni: 'Entrez votre CNI (ID) pour devenir vendeur',
    submit: 'Soumettre',
    message_seller_privately: 'Contacter le vendeur en privé',
    comments: 'Commentaires',
    write_comment: 'Écrire un commentaire...',
    seller_badge: 'Vendeur',
    report: 'Signaler',
    confirm_purchase: 'Confirmer l\'achat',
    ask_question: 'Poser une question',
    proceed_to_payment: 'Passer au paiement',
    interested_in: "Salut ! Je suis intéressé par votre {product} vu dans le flux.",
    search_placeholder: 'Rechercher des produits...',
    filter: 'Filtrer',
    condition_new: 'Neuf',
    condition_used: 'Occasion',
    all: 'Tout',
    clothes: 'Vêtements',
    tech: 'Tech',
    food: 'Nourriture',
    cars: 'Voitures',
    sub_categories: 'Sous-catégories',
    price_range: 'Tranche de prix',
    clear_all: 'Tout effacer',
    apply_filters: 'Appliquer les filtres',
    no_results: 'Aucun résultat trouvé',
    clear_filters_to_see_more: 'Effacez les filtres pour en voir plus',
    shoes: 'Chaussures',
    phones: 'Téléphones',
    furniture: 'Meubles',
    search_categories: 'Rechercher des catégories...',
    more: 'Plus',
    back_to_top: 'Retour en haut',
    electronics: 'Électronique',
    beauty: 'Beauté',
    sports: 'Sports',
    home_garden: 'Maison & Jardin',
    baby: 'Bébé',
    books: 'Livres',
    services: 'Services',
    real_estate: 'Immobilier',
    solar_energy: 'Énergie Solaire',
    agriculture: 'Agriculture',
    hardware: 'Quincaillerie',
    beverages: 'Boissons (Amayoga)',
    industrial_tools: 'Outils Industriels',
    share: 'Partager',
    joined: 'Rejoint',
    view_shop: 'Voir la boutique',
    message_seller: 'Contacter le vendeur',
    buy_now: 'ACHETER MAINTENANT',
    verified_soko_point: 'Point Soko vérifié',
    you_might_also_like: 'Vous pourriez aussi aimer',
    read_more: 'Lire plus',
    read_less: 'Lire moins',
    more_from_seller: 'Plus du vendeur',
    share_success: 'Lien copié dans le presse-papier !',
  },
  rn: {
    nav_home: 'Ahabanza',
    nav_soko: 'Soko',
    nav_sell: 'Kugurisha',
    nav_inbox: 'Ubutumwa',
    nav_profile: 'Umwidondoro',
    buy_via_soko: 'Gura biciye kuri Soko-Live',
    switch_to_seller: 'Ba Umudandaza',
    escrow_status: 'Amahera abitswe',
    ad_placeholder: 'Kwamamaza',
    upload_product: 'Shira ikidandazwa',
    chat_empty: 'Nta butumwa',
    role_buyer: 'Urugero: Umuguzi',
    role_seller: 'Urugero: Umudandaza',
    enter_cni: 'Andika CNI (ID) yawe kugira ube umudandaza',
    submit: 'Emeza',
    message_seller_privately: 'Andikira umudandaza mu mpisho',
    comments: 'Ibitekerezo',
    write_comment: 'Andika igitekerezo...',
    seller_badge: 'Umudandaza',
    report: 'Kurega',
    confirm_purchase: 'Emeza kugura',
    ask_question: 'Baza ikibazo',
    proceed_to_payment: 'Rungika amahera',
    interested_in: "Mwaramutse! Ndashaka kugura {product} nabonye.",
    search_placeholder: 'Rondera ibikoresho...',
    filter: 'Hitamo',
    condition_new: 'Gishasha',
    condition_used: 'Gishaje',
    all: 'Vyose',
    clothes: 'Impuzu',
    tech: 'Ubuhinga',
    food: 'Ibiribwa',
    cars: 'Imiduga',
    sub_categories: 'Ibisata',
    price_range: 'Igiciro',
    clear_all: 'Siba vyose',
    apply_filters: 'Emeza',
    no_results: 'Nta bishitse twabonye',
    clear_filters_to_see_more: 'Siba ivyo wahisemo kugira ubone vyinshi',
    shoes: 'Inkweto',
    phones: 'Terefone',
    furniture: 'Ibikoresho vyo nzu',
    search_categories: 'Rondera ibisata...',
    more: 'Ibindi',
    back_to_top: 'Subira hejuru',
    electronics: 'Ivyuma',
    beauty: 'Ubushiza',
    sports: 'Inkino',
    home_garden: 'Inzu n\'umurima',
    baby: 'Abana',
    books: 'Ibitabo',
    services: 'Ibikorwa',
    real_estate: 'Amazu',
    solar_energy: 'Imirasire y\'izuba',
    agriculture: 'Uburimyi',
    hardware: 'Ivyuma',
    beverages: 'Ibinyobwa (Amayoga)',
    industrial_tools: 'Ivyuma vy\'inganda',
    share: 'Sangira',
    joined: 'Yifatanije',
    view_shop: 'Raba iduka',
    message_seller: 'Vugana n\'uwugurisha',
    buy_now: 'GURA NONAHA',
    verified_soko_point: 'Soko-Point yemejwe',
    you_might_also_like: 'Ibindi ushobora gukunda',
    read_more: 'Soma vyinshi',
    read_less: 'Soma bike',
    more_from_seller: 'Ibindi vy\'uwugurisha',
    share_success: 'Ihuza ryakopewe!',
  }
};

const LanguageContext = createContext<{
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
} | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('en');

  const t = (key: keyof typeof translations['en']) => {
    return translations[lang][key] || translations['en'][key];
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
